Kyra/win game
laptou/koiiword pull request #58
Opened 2021-11-28 04:13 UTC by kyralee22

This PR currently has the winning score threshold set as 4 points so you guys can see what it looks like when a player wins. It will be changed to 100 later. Also, I could not figure out how to restart the game so the commented out parts are my attempts (extracting the main function to another file/module made a dependent cycle, using a ref to house the main function to run later didn't work, I ran into a bunch of logic issues). If you guys can give me guidance on how to restart the game either using main or running the loop with a fresh game state that would be helpful :)

2021-11-29 20:28 UTC, isabellawu90 approved these changes

2021-12-01 01:18 UTC, owenxr requested changes

2021-12-01 01:18 UTC, owenxr commented on bin/main.ml
> +
Can we test the replay code as well?

2021-12-01 02:10 UTC, owenxr commented
For restarting the game after a win:

Instead of thinking about rerunning the main function, think about how you can reset the game state to mimick the beginning of a game. After the `draw` function is run, the `loop` function will be run afterwards. This means even on the win screen, all the keys are still able to be used. We can take advantage of this to return a new game state that mimicks the beginning of a game, essentially creating a restart.

Trying creating field in `game_state` within `state.ml` called `mutable in_play`. You will want to make it mutable because you will want to change this state when you are drawing the win_box. Then, for example, in the `loop` function you can go to the `Enter` key event match and insert a boolean to check this `in_play` state. If `in_play` implies a win condition is met, `LoopResultUpdate` the current state except resetting:
- board to a new board
- players to players with 0 points and a new deck
- entry = SelectStart
- current_player_index = 0
- dict (this should remain the same so nothing to change here)
- in_play reset to represent no winning condition met

2021-12-01 02:15 UTC, owenxr commented
<img width="668" alt="Screen Shot 2021-11-30 at 9 14 19 PM" src="https://user-images.githubusercontent.com/67097401/144159636-14201c00-b30b-41cd-aa27-88fb708dbf26.png">

2021-12-01 02:16 UTC, owenxr commented
> This PR currently has the winning score threshold set as 4 points so you guys can see what it looks like when a player wins. It will be changed to 100 later. Also, I could not figure out how to restart the game so the commented out parts are my attempts (extracting the main function to another file/module made a dependent cycle, using a ref to house the main function to run later didn't work, I ran into a bunch of logic issues). If you guys can give me guidance on how to restart the game either using main or running the loop with a fresh game state that would be helpful :)

Game restart should be implemented with my commit

2021-12-02 19:11 UTC, laptou commented
I think that the win condition should be checked in the update loop and not in the draw function. It's better to keep the state updating code and the drawing code as separate as possible to avoid confusion, and that would make this more consistent with how everything else works. Since there's only one place in the update loop where the player's score can increase (when they are finishing a word entry), you can just check if the new state is one where one of the players has won, and if so, then we return a state that indicates that the game is over.

We could also change `game_state` into an enum that has different variants for different parts of the game, ex.:

```ocaml
type game_state = 
  | Title { selection: title_screen_selection }
  | Gameplay { (* ... *) }
  | Victory { winning_player: int; scores: int list }
  | Options { (* ... *) }
```

2021-12-02 19:11 UTC, laptou requested changes
I think that the win condition should be checked in the update loop and not in the draw function. It's better to keep the state updating code and the drawing code as separate as possible to avoid confusion, and that would make this more consistent with how everything else works. Since there's only one place in the update loop where the player's score can increase (when they are finishing a word entry), you can just check if the new state is one where one of the players has won, and if so, then we return a state that indicates that the game is over.

We could also change `game_state` into an enum that has different variants for different parts of the game, ex.:

```ocaml
type game_state = 
  | Title { selection: title_screen_selection }
  | Gameplay { (* ... *) }
  | Victory { winning_player: int; scores: int list }
  | Options { (* ... *) }
```

2021-12-14 20:37 UTC, laptou commented
superseded by #68

2021-12-14 20:37 UTC, closed without merging